server:
  port: 8080

spring:
  application:
    name: north-wollo-tourism

  datasource:
    url: jdbc:postgresql://localhost:5432/north_wollo_tourism
    username: postgres
    password: 123123Aa
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: create-drop

  jackson:
    serialization:
      write-dates-as-timestamps: false

# JWT Configuration
app:
  jwt:
    secret: northWolloSecretKey2025
    expiration: 86400000   # 24 hours (milliseconds)

# Swagger (OpenAPI)
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
